# Generated by Django 5.2.1 on 2025-05-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_stock_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
