# Generated by Django 5.2.1 on 2025-05-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_stock_delete_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.stock",
            ),
        ),
    ]
