# Generated by Django 5.2.1 on 2025-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_stock_alter_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
