# Generated by Django 5.2.1 on 2025-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_stock_last_updated_alter_stock_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
