# Generated by Django 5.2.1 on 2025-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="products",
            field=models.ManyToManyField(related_name="stocks", to="products.product"),
        ),
    ]
